### ISSUE TITLE
Creating installers

### ISSUE THREAD

**Issue by sardylan** [sardylan/qfm1000#6]
Create Windows, Linux and MAC automatic installers

**Comment by sardylan** [comment]
#7

**Comment by sardylan** [comment]
CPack can generate Windows MSI installer and Linux DEB packages.
Still working on a Mac environment

**Comment by ea3iav** [comment]
Hello! Is there any info to make the installer in Windos? I am struggling to advance but I don't even know where to start from
thank you in advance

**Comment by sardylan** [comment]
Hi,
Windows installers are made using CPack integration for WiX Toolset, a framework for creating MSI (MicroSoft Installer) packages.
If you are trying to compile and create your own package, you shold have both CMake (which include CPack) and WiX Toolset already installed on Windows.

**Comment by ea3iav** [comment]
Hello! I dowloaded your zip and it works! It lets me change frewquencies and save new bin file! Awesome!
Now I am trying to make that new channels work on my fm1000


Thank you very much!

El 22 de noviembre de 2020, 23:38, Luca Cireddu <notifications@github.com> escribió:






Hi,
Windows installers are made using CPack integration for WiX Toolset, a framework for creating MSI (MicroSoft Installer) packages.
If you are trying to compile and create your own package, you shold have both CMake (which include CPack) and WiX Toolset already installed on Windows.

**Comment by ea3iav** [comment]
https://youtu.be/MxlM9YBMLO8
