### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sardylan/qfm1000#8]
You may remove the next lines after the Wire.requestFrom() in "qfm1000/arduino/eeprom_programmer/eeprom_programmer.ino" :
```
while (!Wire.available())
  delay(1);
```
There is nothing to wait for.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by sardylan** [comment]
Many thanks...
As suggested, cycle and wait command removed on https://github.com/sardylan/qfm1000/commit/2d47f070bbb640ccf92fcf8e87e90e7547f87ac5.

**Comment by Koepel** [comment]
Why is there a `Wire.available();` ?
The Wire.available() returns the number of bytes that are in the buffer in the Wire library. That is all it does. It does not wait for something, it does not set something right, it does not do anything on the I2C bus.

**Comment by sardylan** [comment]
You are absolutely right...
Just forget to remove the line...
Many thanks...

**Comment by sardylan** [comment]
Fixed on https://github.com/sardylan/qfm1000/commit/387c3ba81c2badbfc71e54f11e7899fcb3b4a38c
